In [1]:
import pandas as pd
import numpy as np
import pickle as pkl
from sklearn import preprocessing

In [2]:
model = pkl.load(open("model.pkl", "rb"))

In [3]:
#After scaling

# array([[1.90718024],
#        [1.78304975],
#        [1.89191532],
#        [1.88179366],
#        [2.0639836 ]])

In [4]:
#Before scaling

# array([[17585.15],
#        [17396.9 ],
#        [17562.  ],
#        [17546.65],
#        [17822.95]])

In [5]:

hana = np.array([[17585.15],
       [17396.9 ],
       [17562.  ],
       [17546.65],
       [17822.95]])

hana = preprocessing.scale(hana)

hana

model.predict(hana)

array([14853.2469323 , 12846.62626271, 14606.4832218 , 14442.86235977,
       17388.0378764 ])

In [6]:
hanr = np.array([[17685.15],
       [17496.9 ],
       [17362.  ],
       [17746.65],
       [17022.95]])

hanr = preprocessing.scale(hanr)

hanr

model.predict(hanr)

array([16083.53406204, 15020.42114866, 14258.59415256, 16430.84585048,
       12343.86143924])

In [7]:
val = model.predict(hanr)

In [8]:
val[1]

15020.4211486579

In [9]:
val = np.around(val, 2)

In [10]:
val

array([16083.53, 15020.42, 14258.59, 16430.85, 12343.86])

In [11]:
lis = [[17685.15],
       [17496.9 ],
       [17362.  ],
       [17746.65],
       [17022.95]]

In [12]:
lis

[[17685.15], [17496.9], [17362.0], [17746.65], [17022.95]]

In [13]:
lis_array = np.array(lis)

In [14]:
lis_array

array([[17685.15],
       [17496.9 ],
       [17362.  ],
       [17746.65],
       [17022.95]])

In [15]:
val

array([16083.53, 15020.42, 14258.59, 16430.85, 12343.86])

In [16]:
# print("what ever\n{}\n{}\n{}\n{}\n{}".format(val[0],val[1],val[2],val[3],val[4]))

In [17]:
# import seaborn as sns
# import matplotlib.pyplot as plt

In [18]:
# sns.lineplot(data = val)
# plt.title("Stock trend for next five days")

# ra = plt.show()

In [19]:
# text = "The trend of next five days\nfirst day{}\nsecond day{}\nthird day{}\nfourth day{}\nfifth day{}".format(val[0], val[1], val[2], val[3], val[4])

In [20]:
# print(text)